<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GejalaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('gejalas')->insert([
            [
                'kode_gejala' => 'G001',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah PC anda mengalami mati secara tiba tiba ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G002',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah PC anda tidak dapat dihidupkan dengan cara apapun ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G003',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah PC anda mengalami booting yang gagal ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G004',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah beberapa komponen yang terdapat pada motherboard tidak terdeteksi ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G005',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah PC anda mengalami shutdown mendadak ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G006',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah port atau slot yang terdapat pada motherboard anda tidak berfungsi ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G007',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah PC anda mengalami bunyi beep tidak normal ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G008',
                'kode_kerusakan' => 'K001',
                'gejala' => 'Apakah PC anda mengalami overheat ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G009',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah driver VGA pada PC anda tidak terbaca ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G010',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda mengalami performa yang lemah ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G011',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda mengalami Blue screen ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G012',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda tidak ada tampilan pada monitor ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G013',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda mengalami artefak grafis pada monitor ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G014',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda mengalami crash atau freeze saat bermain game ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G015',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda mengalami bunyi kipas tidak normal ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G016',
                'kode_kerusakan' => 'K002',
                'gejala' => 'Apakah PC anda mengalami warna monitor yang tidak normal ?',
                'bobot' => 12.5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G017',
                'kode_kerusakan' => 'K003',
                'gejala' => 'Apakah PC anda mengalami booting yang gagal ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G018',
                'kode_kerusakan' => 'K003',
                'gejala' => 'Apakah PC anda terdapat garis lurus pada layar ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G019',
                'kode_kerusakan' => 'K003',
                'gejala' => 'Apakah PC anda mengalami layar berkedip terus menerus ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G020',
                'kode_kerusakan' => 'K003',
                'gejala' => 'Apakah aplikasi atau sistem operasi pada PC anda sering crash ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G021',
                'kode_kerusakan' => 'K004',
                'gejala' => 'Apakah PC anda tidak bisa menyala ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G022',
                'kode_kerusakan' => 'K004',
                'gejala' => 'Apakah PC anda mengalami bunyi aneh pada power supply?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G023',
                'kode_kerusakan' => 'K004',
                'gejala' => 'Apakah PC anda mengalami bau gosong atau hangus ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G024',
                'kode_kerusakan' => 'K004',
                'gejala' => 'Apakah PC anda mengalami LED atau lampu indikator yang berkedip pada power supply ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G025',
                'kode_kerusakan' => 'K005',
                'gejala' => 'Apakah PC anda mengalami transfer data yang lambat ?',
                'bobot' => 20.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G026',
                'kode_kerusakan' => 'K005',
                'gejala' => 'Apakah PC anda mengalami file atau folder yang hilang ?',
                'bobot' => 20.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G027',
                'kode_kerusakan' => 'K005',
                'gejala' => 'Apakah PC anda mengalami error saat menyalin atau memindahkan file ?',
                'bobot' => 20.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G028',
                'kode_kerusakan' => 'K005',
                'gejala' => 'Apakah PC anda mengalami frequent freezes atau crash ?',
                'bobot' => 20.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G029',
                'kode_kerusakan' => 'K005',
                'gejala' => 'Apakah PC anda tidak bisa booting ?',
                'bobot' => 20.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G030',
                'kode_kerusakan' => 'K006',
                'gejala' => 'Apakah PC anda tidak menyala ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G031',
                'kode_kerusakan' => 'K006',
                'gejala' => 'Apakah PC anda sering restart dan shutdown mendadak ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G032',
                'kode_kerusakan' => 'K006',
                'gejala' => 'Apakah PC anda mengalami overheating ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_gejala' => 'G033',
                'kode_kerusakan' => 'K006',
                'gejala' => 'Apakah PC anda mengalami frequent freezes atau crash ?',
                'bobot' => 25.0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
